name: Build and Deploy Expo App

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Expo CLI
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Build Android APK
        run: eas build --platform android --profile preview --non-interactive --wait

      - name: Get build URL
        run: |
          BUILD_URL=$(eas build:list --platform android --limit 1 --json | jq -r '.[0].artifacts.buildUrl')
          echo "Build URL: $BUILD_URL"
          echo "BUILD_URL=$BUILD_URL" >> $GITHUB_ENV

      - name: Comment on PR (if applicable)
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 **New build ready!**\n\nDownload APK: ${process.env.BUILD_URL}\n\nScan QR code on the build page for easy installation.`
            })

      - name: Create Release (on main branch)
        if: github.ref == 'refs/heads/main'
        uses: actions/github-script@v7
        with:
          script: |
            const { data: release } = await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: `v${Date.now()}`,
              name: `Release ${new Date().toISOString().split('T')[0]}`,
              body: `🚀 **New Android build available!**\n\n**Download:** ${process.env.BUILD_URL}\n\n**How to install:**\n1. Click the download link above\n2. Scan the QR code on the page\n3. Install the APK on your Android device\n\n**Changes:**\n${context.payload.head_commit.message}`,
              draft: false,
              prerelease: false
            });
            console.log(`Release created: ${release.html_url}`)
